title: Matt Kowal's Blog
author: Matthew Kowal
email: matthew.kowal@ryerson.ca
description: > # this means to ignore newlines until "show_excerpts:"
  Computer Vision // Mathematics // Deep Learning
  Finding ways to better train neural networks. 

show_excerpts: false # set to true to show excerpts on the homepage
use_math: true

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: MatthewKowal9
    github:  MKowal2

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md
- publications.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
